name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: clj2nix
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
      - run: |
          # Build the binary
          nix -L build
          # Generate a nix file
          ./result/bin/clj2nix ./test/deps.test.edn ./test/deps.test.nix
          # Make a sanity check
          nix-build -E 'with import <nixpkgs> {}; callPackage ./test/test.nix {}'
